apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: testgo0602a
  janus-idp.io/tekton: testgo0602a
  backstage.io/kubernetes-id: testgo0602a
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: testgo0602a
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
