apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testgo0602a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testgo0602a 
  name: testgo0602a
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testgo0602a 
